name: pypi-publish

on: push

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Install pypa
      run: python3 -m pip install build --user
    - name: Build wheel
      run: python3 -m build
    - name: Store package
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
  publish:
    name: Publish package to pypi
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/gpt2-prot
    permissions:
      id-token: write
    steps:
    - name: Download artefacts
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
